[package]
name = "exonum-btc-anchoring"
version = "0.8.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/bitcoin-anchoring/"
repository = "https://github.com/exonum/exonum-btc-anchoring"
documentation = "https://docs.rs/exonum-btc-anchoring"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "bitcoin", "anchoring"]
categories = ["database-implementations"]
description = "An Exonum service that provides anchoring to Bitcoin blockchain."

[badges]
travis-ci = { repository = "exonum/exonum-btc-anchoring" }

[dependencies]
exonum = "0.9.0"
exonum_bitcoinrpc = "0.5.1"
exonum-testkit = "0.9.0"

bitcoin = "0.13.1"
btc-transaction-utils = "0.2.0"
byteorder = "1.0.0"
clap = "2.22.1"
derive_more = "0.10.0"
display_derive = "0.0.0"
failure = "0.1.1"
failure_derive = "0.1.1"
log = "=0.4.3"
maplit = "1.0.1"
mount = "0.4.0"
rand = "0.4.2"
router = "0.6.0"
secp256k1 = "0.9.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
serde_str = "0.1.0"
tempdir = "0.3.5"
toml = "0.4.0"
matches = "0.1.6"

[dev-dependencies]
exonum-configuration = "0.9.0"
libc = "0.2.21"
pretty_assertions = "0.5.1"
proptest = "0.7.0"

[features]
default = []
testnet_tests = []
